### ISSUE TITLE
Nested class selectors don't work

### ISSUE THREAD

**Issue by stevage** [mapbox/carto#291] opened 2013-08-09 01:09 UTC
Given a layer with class "foo bar", this works:

```
.foo { ... }
.bar { ... }
```

But this doesn't:

```
.foo {
  .bar {
     ....
   }
}
```

This is annoying, because I'd like to set classes on layers (I'm trying to show the routes of some trips I've been on, with properties like the year, number of people, type of trip etc). It would look something like this:

```
.trip {
   line-width: 1;
   .size-medium { line-width: 2; }
   .size-big {line-width: 4; }
   line-color: green;
   .year-2012 { line-color: blue; }
   .year-2013 { line-color: orange;  }

}
```

The workaround at this point seems to be one rule per layer, or loading the data into PostGIS and using attribute selectors.

**Comment by nebulon42** [comment] 2016-12-24 12:32
@stevage I have added a test case for this and could not reproduce the problem. Maybe I understood something wrong, but since your original MML is no longer reachable I can't judge what was different for you.

It would be great if you could again provide input, otherwise I will close this issue when releasing 0.17.

**Comment by stevage** [comment] 2016-12-24 23:25
Hi! I'm not really using Cartocss atm so happy for you to close.

**Closed** 2016-12-25 08:30 UTC
Labels: bug, needs-test
