### ISSUE TITLE
image-filters doc missing

### ISSUE THREAD

**Issue by cmyk** [mapbox/carto#396] opened 2015-07-27 16:33 UTC
"(see the image-filters doc for how they work on a separate canvas)"
Yeah, but where?

**Comment by kitsunde** [comment] 2015-10-22 17:29
I've also ran into this problem. Specifically I've been trying to figure out what the parameter order of `scale-hsla` is.

**Comment by nebulon42** [comment] 2016-02-27 12:09
Related, duplicate of #285.

**Closed** 2016-03-01 07:00 UTC
Labels: documentation
